import 'api_client.dart';

class VideoCallService {
  final ApiClient _apiClient = ApiClient();

  /// 🔹 Fetch Agora token for a given channel and uid
  Future<Map<String, dynamic>> fetchAgoraToken({
    required String channel,
    required String uid,
  }) async {
    return await _apiClient.get(
      "videocall/token",
      queryParams: {"channel": channel, "uid": uid},
      useAuth: true,
    );
  }

  /// 🔹 Start video call (create record in DB)
  Future<Map<String, dynamic>> startCall({
    required String appointmentId,
    required String doctorId,
    required String patientId,
    required String channelName,
  }) async {
    final body = {
      "doctor": doctorId,
      "user": patientId,
      "appointment":
          appointmentId, // required, pass the relevant appointment ID
      "channelName": channelName,
      "startedAt": DateTime.now().toIso8601String(), // required
      // Optional fields
      "endedAt": null,
      "videoUrl": null,
      "isBackupAvailable": false,
    };

    return await _apiClient.post("videocall/start", body, useAuth: true);
  }

  /// 🔹 End call & update backup status (if app-side recording or upload)
  Future<Map<String, dynamic>> endCall({
    required String callId,
    required bool isBackupAvailable,
    String? videoUrl, // optional upload if generated by app-side
  }) async {
    final body = {"backupAvailable": isBackupAvailable, "videoUrl": videoUrl};

    return await _apiClient.post("videocall/end/$callId", body, useAuth: true);
  }

  /// 🔹 Fetch list of video call history for the logged-in user
  Future<Map<String, dynamic>> getVideoCallHistory() async {
    return await _apiClient.get("videocall/list", useAuth: true);
  }
}
