import 'api_client.dart';

class VideoCallService {
  final ApiClient _apiClient = ApiClient();

  /// 🔹 Fetch Agora token for a given channel and uid
  Future<Map<String, dynamic>> fetchAgoraToken({
    required String channel,
    required int uid,
  }) async {
    return await _apiClient.get(
      "videocalls/token",
      queryParams: {"channel": channel, "uid": uid},
      useAuth: true,
    );
  }

  /// 🔹 Start video call (create record in DB)
  Future<Map<String, dynamic>> createVideocall({
    required String patientId,
    required String doctorId,
    required String appointmentId,
  }) async {
    final body = {
      "doctor": doctorId,
      "patient": patientId,
      "appointment":
          appointmentId, // required, pass the relevant appointment ID
    };

    return await _apiClient.post("videocalls", body, useAuth: true);
  }

  /// 🔹 End call & update backup status (if app-side recording or upload)
  Future<Map<String, dynamic>> updateCall({
    required String callId,
    required String status,
    String? videoUrl, // optional upload if generated by app-side
  }) async {
    final body = {"videoUrl": videoUrl, "status": status};
    return await _apiClient.put("videocalls/$callId", body, useAuth: true);
  }

  /// 🔹 Fetch list of video call history for the logged-in user
  Future<Map<String, dynamic>> getVideoCallHistory() async {
    return await _apiClient.get("videocalls", useAuth: true);
  }
}
