name: iOS Debug Build

on:
  workflow_dispatch:   # run manually
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'
          channel: stable


      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (debug)
        run: flutter build ios --debug --no-codesign --dart-define=API_BASE_URL=https://healthcare-backend-production-83a6.up.railway.app

      - name: Build iOS Debug IPA (unsigned)
        run: flutter build ios --debug --no-codesign --dart-define=API_BASE_URL=https://healthcare-backend-production-83a6.up.railway.app
      - name: Package unsigned IPA
        run: |
          mkdir -p build/ios/ipa
          xcrun -sdk iphoneos PackageApplication -v build/ios/Debug-iphoneos/Runner.app -o build/ios/ipa/Runner.ipa
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-ipa
          path: build/ios/ipa/*.ipa



